apiVersion: v1
kind: ConfigMap
data:
  spark.driver.cores: "0.5"
  spark.driver.memory: "1g"
  spark.kubernetes.executor.request.cores: "0.5"
  spark.kubernetes.allocation.batch.size: "10"
  spark.executor.memory: "1g"
  spark.executor.instances: "1"
  spark.kubernetes.driver.volumes.persistentVolumeClaim.eventlog.mount.path: {{ .Values.storage.eventlogDir  | quote }}
  spark.kubernetes.driver.volumes.persistentVolumeClaim.eventlog.mount.readOnly: "false"
  spark.kubernetes.driver.volumes.persistentVolumeClaim.eventlog.options.claimName: {{ printf "%s-%s" .Release.Name .Values.storage.eventlogPvc | quote }}
  spark.kubernetes.executor.volumes.persistentVolumeClaim.eventlog.mount.path: {{ .Values.storage.eventlogDir  | quote }}
  spark.kubernetes.executor.volumes.persistentVolumeClaim.eventlog.mount.readOnly: "false"
  spark.kubernetes.executor.volumes.persistentVolumeClaim.eventlog.options.claimName: {{ printf "%s-%s" .Release.Name .Values.storage.eventlogPvc | quote }}
  spark.kubernetes.driver.volumes.persistentVolumeClaim.conf.mount.path: {{ .Values.storage.confDir | quote }}
  spark.kubernetes.driver.volumes.persistentVolumeClaim.conf.mount.readOnly: "true"
  spark.kubernetes.driver.volumes.persistentVolumeClaim.conf.options.claimName: {{ printf "%s-%s" .Release.Name .Values.storage.confPvc | quote }}
  spark.kubernetes.executor.volumes.persistentVolumeClaim.conf.mount.path: {{ .Values.storage.confDir | quote }}
  spark.kubernetes.executor.volumes.persistentVolumeClaim.conf.mount.readOnly: "true"
  spark.kubernetes.executor.volumes.persistentVolumeClaim.conf.options.claimName: {{ printf "%s-%s" .Release.Name .Values.storage.confPvc | quote }}
  spark.kubernetes.driver.volumes.persistentVolumeClaim.jar.mount.path: {{ .Values.storage.jarDir | quote }}
  spark.kubernetes.driver.volumes.persistentVolumeClaim.jar.mount.readOnly: "true"
  spark.kubernetes.driver.volumes.persistentVolumeClaim.jar.options.claimName: {{ printf "%s-%s" .Release.Name .Values.storage.jarPvc | quote }}
  spark.kubernetes.executor.volumes.persistentVolumeClaim.jar.mount.path: {{ .Values.storage.jarDir | quote }}
  spark.kubernetes.executor.volumes.persistentVolumeClaim.jar.mount.readOnly: "true"
  spark.kubernetes.executor.volumes.persistentVolumeClaim.jar.options.claimName: {{ printf "%s-%s" .Release.Name .Values.storage.jarPvc | quote }}
metadata:
  name: spark-defaults-conf-config-map
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "livy.name" . }}
    helm.sh/chart: {{ include "livy.chart" . }}
