apiVersion: v1
kind: Service
metadata:
  name: {{ include "livy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "livy.name" . }}
    helm.sh/chart: {{ include "livy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: livy-port
    protocol: TCP
    name: livy-port
{{- if .Values.service.additionalPorts }}
  {{- range .Values.service.additionalPorts }}
  - port: {{ .port }}
    targetPort: {{ .name }}
    protocol: TCP
    name: {{ .name }}
  {{- end }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "livy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
