apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-history-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "spark-history-server.name" . }}
    helm.sh/chart: {{ include "spark-history-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  enableGCS: {{ .Values.gcs.enableGCS | quote }}
  enableS3: {{ .Values.s3.enableS3 | quote }}
  enableWASBS: {{ .Values.wasbs.enableWASBS | quote }}
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- if .Values.storage.enableStorage }}
  {{- range $key, $val := .Values.storage }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- else if .Values.gcs.enableGCS }}
  {{- range $key, $val := .Values.gcs }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- else if .Values.s3.enableS3 }}
  {{- range $key, $val := .Values.s3 }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- else if .Values.wasbs.enableWASBS }}
  {{- range $key, $val := .Values.wasbs }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- else }}
  {{- range $key, $val := .Values.hdfs }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
